// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0gS7IlvGiDKdSlDKw66tvYJiVsfWVwAg',
    appId: '1:919908193240:web:b910e2beb535b2505658ad',
    messagingSenderId: '919908193240',
    projectId: 'godsseo-app',
    authDomain: 'godsseo-app.firebaseapp.com',
    storageBucket: 'godsseo-app.appspot.com',
    measurementId: 'G-SY8201LFEP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJ1-qRXld4hksgn30RT3WB-1O9HbfblGU',
    appId: '1:919908193240:android:7453bb97bab2bbf55658ad',
    messagingSenderId: '919908193240',
    projectId: 'godsseo-app',
    storageBucket: 'godsseo-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDseTNS6Hvn-ABZ1Yj8laCsiWx5Cs_ZqFs',
    appId: '1:919908193240:ios:235063f91ce843705658ad',
    messagingSenderId: '919908193240',
    projectId: 'godsseo-app',
    storageBucket: 'godsseo-app.appspot.com',
    iosBundleId: 'com.example.godsseo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDseTNS6Hvn-ABZ1Yj8laCsiWx5Cs_ZqFs',
    appId: '1:919908193240:ios:f173f4d47f6b0ae45658ad',
    messagingSenderId: '919908193240',
    projectId: 'godsseo-app',
    storageBucket: 'godsseo-app.appspot.com',
    iosBundleId: 'com.example.godsseo.RunnerTests',
  );
}
